spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/gym_management_system?createTableIfNotExist=true"
    username: "root"
    password: "Pintush@12345"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
